site_name: IOS Swift application
theme:
  name: material
  palette:
    - scheme: dracula
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
nav:
  - Home: index.md
  - Swift:
      - Basics: swift/basics.md
      - Libraries: swift/libraries.md
      - Common Design Pattern: swift/pattern.md
      - Applied Projects: swift/applied.md
  - DailyForge:
      - Wireframe: DailyForge/wireframe.md
      - Web Design: DailyForge/webDesign.md
      - Modules: DailyForge/modules.md
      - App Documentation: DailyForge/appDocs.md
  - Resume: resume.md



